### ISSUE TITLE
Telemetry Readings Have "Tick"

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/Faraday-Firmware#15]
I noticed that the ADC readings seemed to have a "tick" to them with my new telemetry application. Then I checked the Rev B Faraday with the Balloon Launch software (8/2016) using the same firmware and there it was, still ticking:

**ADC Channel**
![image](https://cloud.githubusercontent.com/assets/331540/19467130/5d87cb9a-94c4-11e6-9e5e-3f6deab383bb.png)

**GPS Altitude**
![image](https://cloud.githubusercontent.com/assets/331540/19467213/cfd39cce-94c4-11e6-942f-d5740b11a278.png)

This indicates it's not my new parser, it's in the firmware. Turns out it's also on the GPS data so this seems to clearly be in the firmware land and not just with the ADC code. What did you recently change in firmware to possibly cause this?

**Comment by kb1lqc** [comment]
That's weird, if I plot Altitude (Radio Unit) yellow and AP Altitude (Local Unit) green which in this case is just my own unit then the local unit data doesn't appear to have the "ticks". Since this should be just my locally connected unit I would expect both of these to be exactly the same, the Balloon Software I tested this on never did this...

![image](https://cloud.githubusercontent.com/assets/331540/19467356/9b4003b6-94c5-11e6-98b4-2bc8855b8288.png)

**Comment by kb1lqd** [comment]
@kb1lqc Can you post a snippet/file of just relevant data? Are the ticks actually IN the raw data from telemetry/SQLite?

**Comment by kb1lqc** [comment]
@kb1lqd 
Actual Board Temp: Column AF (Labaled ADC8)
VCC Battery: Column AE (Labeled Board Temp)

[telemtest.zip](https://github.com/FaradayRF/Faraday-Firmware/files/535553/telemtest.zip)

**Comment by kb1lqc** [comment]
OK I'm closing this. No root cause, a byproduct of moving quick over many different items and starting our manufacturing run. Will not be acceptable in the future but for now need to accept it. I assume this was fixed with something @kb1lqd changed in the handling of telemetry. Likely while addressing the VCC and board temperature firmware bugs

Below is the current plot of most ADC channels using "Faraday_D1_Release.txt" firmware file and the current master software (https://github.com/FaradayRF/Faraday-Software/commit/4c12933766e6f7c8891d682348f39f542e878552)

![adcs_issue_15](https://cloud.githubusercontent.com/assets/331540/22631159/d738a61e-ebbb-11e6-85f1-54f35d884cee.png)

All seems well.
