### ISSUE TITLE
RF not receiving due to callsign settings

### ISSUE THREAD

**Issue by kb1lqd** [FaradayRF/Faraday-Firmware#69]
## Summary
Working with an owner of a Faraday REV D1 it has been found that certain callsign or other settings may cause the RF to cease reception. Configurations known to produce proper operation allow transmissions but the units do not recieve data into Proxy. Known good units have reproduced the problems thus indicating a likely firmware bug.

## Problem Explanation
Owner K6YAP reported problems receiving signals from Faraday. I have reproduced the problems using his exact callsign in an RF test setup with known good units. Telemetry broadcasts RF layer 2 MAC packets addressed to "CQCQCQ" for general broadcasting but debugging has shown:

Unit 1:
Callsign = K6YAP
NodeID = 0

Unit 2:
Callsign = K6YAP
NodeID = 1

* Unit TX: Destination = "CQCQCQ"
* Unit RX: Destination = "CQCQC0xD0" where the 0xD0 is a non-ASCII hex value and likely a random memory byte during packet creation (may not be the same on all devices).

When receiving packets the incorrect receive destination callsign shown above causes the check to fail and packet to get dropped from BOTH the callsign check and CQCQCQ check. This occurred on both units receiving each-others telemetry and is the most probable cause of receive path failing for K6YAP.

#### Software 
* Firmware = Master
* Software = Master

#### Hardware
* Unit SN's (KB1LQD's): SN12, SN13
* Operating System = Windows 10

# Supporting Information

### Receiver Layer 2 MAC "CQCQCQ" Destination Check Fail

![image](https://cloud.githubusercontent.com/assets/339144/23396848/a073094e-fd4a-11e6-9c50-dc0543db45a0.png)

### Receiver Housekeeping Pre-Packet Parse

![image](https://cloud.githubusercontent.com/assets/339144/23396990/3b1fe3f4-fd4b-11e6-862a-9dd86fe11d9e.png)

### Receiver RF ISR

'CQCQC' was received at the very front of the RX byte path :(

![image](https://cloud.githubusercontent.com/assets/339144/23397026/731c7d94-fd4b-11e6-902a-cd26e3cfaab5.png)

### Transmit()

Clearly shown in the TX buffer is the incorrect "CQCQC"...

![image](https://cloud.githubusercontent.com/assets/339144/23397179/392a6ef6-fd4c-11e6-94ba-3a7ebbeb7763.png)

### rf_rawpacket_tx() PUT RF Transmit FIFO 

Error in destination is still present.

![image](https://cloud.githubusercontent.com/assets/339144/23397330/e3fca66e-fd4c-11e6-9cb9-6cfaddb2c411.png)

### rf_tx_datalink_packet()

Error is present during layer 2 packet TX creation.

![image](https://cloud.githubusercontent.com/assets/339144/23397416/472ae55c-fd4d-11e6-9d4f-2e4035a0e2d2.png)

### rf_service_tx()

Error is present.

![image](https://cloud.githubusercontent.com/assets/339144/23397454/70dfd11e-fd4d-11e6-86be-67d25e8b421d.png)

### app_telem_rf_housekeeping()

BOOM! I see the bug right here.

![image](https://cloud.githubusercontent.com/assets/339144/23397539/d1720b28-fd4d-11e6-85f3-8ac0cd17a54f.png)

The destination callsign is copied into the packet during creation with length equal to the SOURCE callsign. K6YAP is a 5 letter callsign but 'CQCQCQ' is 6. This is the bug right here causing the 'CQCQC' plus the extra random byte due to the receiver correctly receiving a destination callsign length of 6 and that last byte is a random uninitialized byte.

# Bug Confirmation
In Telem_RF.c the function app_telem_rf_housekeeping() uses the SOURCE callsign length to copy the DESTINATION callsign into the packet buffer during creation. Since K6YAP is 5 letters the "CQCQCQ" was copied as "CQCQC" and thus caused the receiver to throw out the packets.

![image](https://cloud.githubusercontent.com/assets/339144/23397539/d1720b28-fd4d-11e6-85f3-8ac0cd17a54f.png)
# Bug Solution

I changed the length check for destination callsign from `RF_L2_source_callsign_len` to the correct `RF_L2_destination_callsign_len`.

![image](https://cloud.githubusercontent.com/assets/339144/23397825/f54f9334-fd4e-11e6-9108-92a898469cab.png)

Confirmed RF telemetry is now working when it previously did not!

![image](https://cloud.githubusercontent.com/assets/339144/23397894/29ba00be-fd4f-11e6-90ef-2083f3bdb1f3.png)

**Comment by kb1lqc** [comment]
Nice work @kb1lqd !

**Comment by kb1lqd** [comment]
Created firmware branch https://github.com/FaradayRF/Faraday-Firmware/commit/c1489a4c5d4c69d2822510d482b463ef437bceff

**Comment by kb1lqd** [comment]
@kb1lqc OK I'm not sure how you want to review this. Did you want to run it or just review the single variable change and approve?

If I make a pull request I'm going to have to update the firmware variable. I'd like K6YAP to attempt to program using the BSL loader but knowing he's on a Mac I'm not sure if it will work out of the box. I guess that may be the next project.

**Comment by kb1lqd** [comment]
@kb1lqc and Reilly, can you try using the BSL to program this into your units and verify working?

[Faraday_D1_Release_Bug_69.txt](https://github.com/FaradayRF/Faraday-Firmware/files/806165/Faraday_D1_Release_Bug_69.txt)

I have not tried the BSL on anything but windows. It uses an .exe so maybe it'll work under Wine.

https://github.com/FaradayRF/Faraday-Software/tree/master/Firmware_Bootstrap_Loader

Getting BSL cross platform may be the next step as this needs to be pushed to ALL Faraday owners in an official release. We also should point out this bug to anyone got/getting units with the currently (initial release) firmware.

**Comment by kb1lqd** [comment]
Uploaded below is known good BUG 59 bootstraploading ZIP.

[BUG_69_Firmware_Bootstrap_Loader.zip](https://github.com/FaradayRF/Faraday-Firmware/files/809824/BUG_69_Firmware_Bootstrap_Loader.zip)

**Comment by binaryfox0** [comment]
I've verified that the firmware from the ZIP above fixes my issues.

**Comment by reillyeon** [comment]
I've verified that firmware from the ZIP file above fixes this issue.

**Comment by kb1lqd** [comment]
Fixed in #70
